### ISSUE TITLE
Getting "WRONGTYPE Operation against a key holding the wrong kind of value"

### ISSUE THREAD

**Issue by softfish** [softfish/laravel-redis-ui#10]
There is an issue when I try to display the redis default database. And while I have the laravel queue drive set to redis, the jobs will now store on the redis database.

This queues:default value is a large range of structure - array in this case and is no longer a string any more. So the API are getting the exception from the redis client while I am using $redis->get($key).

Result:
"WRONGTYPE Operation against a key holding the wrong kind of value"

I am packaging up a fix for that.  So we can display a small section of it. (because it is too big). Will think of a way to display this type of value.

**Comment by feiarkade** [comment]
Just published v1.1.5 to fix the display issue with error "WRONGTYPE Operation against a key holding the wrong kind of value".

This version should have unblock the display from the interface. The display of the zset and lrange type data will still restricted. We couldn't update the content for these type of data yet in redis.

Will need to think of a better way to handle these data type in the future version.

**Comment by softfish** [comment]
Just published v1.1.5 to fix the display issue with error "WRONGTYPE Operation against a key holding the wrong kind of value".

This version should have unblock the display from the interface. The display of the zset and lrange type data will still restricted. We couldn't update the content for these type of data yet in redis.

Will need to think of a better way to handle these data type in the future version.
